
# Ce fichier est chargé automatiquement par Docker Compose en développement.
# Il surcharge compose.yaml pour ajouter des options propres au dev local.

services:
  database:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
