<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627034431 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, research_project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_913A8281D27719F4 ON project_activity (research_project_id)');
        $this->addSql('CREATE INDEX IDX_913A8281A76ED395 ON project_activity (user_id)');
        $this->addSql('CREATE TABLE project_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, invited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, research_project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67401132D27719F4 ON project_member (research_project_id)');
        $this->addSql('CREATE INDEX IDX_67401132A76ED395 ON project_member (user_id)');
        $this->addSql('CREATE TABLE sub_project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, name VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, status VARCHAR(50) DEFAULT \'active\' NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, research_project_id INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_506B8C1AD27719F4 ON sub_project (research_project_id)');
        $this->addSql('CREATE INDEX IDX_506B8C1AA76ED395 ON sub_project (user_id)');
        $this->addSql('CREATE INDEX IDX_506B8C1A8CDE5729 ON sub_project (type)');
        $this->addSql('ALTER TABLE project_activity ADD CONSTRAINT FK_913A8281D27719F4 FOREIGN KEY (research_project_id) REFERENCES research_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_activity ADD CONSTRAINT FK_913A8281A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132D27719F4 FOREIGN KEY (research_project_id) REFERENCES research_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sub_project ADD CONSTRAINT FK_506B8C1AD27719F4 FOREIGN KEY (research_project_id) REFERENCES research_project (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sub_project ADD CONSTRAINT FK_506B8C1AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chapter ADD sub_project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E3AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F981B52E3AA68C51 ON chapter (sub_project_id)');
        $this->addSql('ALTER TABLE document ADD sub_project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A763AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D8698A763AA68C51 ON document (sub_project_id)');
        $this->addSql('ALTER TABLE interaction ADD sub_project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA73AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_378DFDA73AA68C51 ON interaction (sub_project_id)');
        $this->addSql('ALTER TABLE project ADD sub_project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE3AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE3AA68C51 ON project (sub_project_id)');
        $this->addSql('ALTER TABLE research_project ADD is_template BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE research_project RENAME COLUMN name TO title');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_activity DROP CONSTRAINT FK_913A8281D27719F4');
        $this->addSql('ALTER TABLE project_activity DROP CONSTRAINT FK_913A8281A76ED395');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132D27719F4');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132A76ED395');
        $this->addSql('ALTER TABLE sub_project DROP CONSTRAINT FK_506B8C1AD27719F4');
        $this->addSql('ALTER TABLE sub_project DROP CONSTRAINT FK_506B8C1AA76ED395');
        $this->addSql('DROP TABLE project_activity');
        $this->addSql('DROP TABLE project_member');
        $this->addSql('DROP TABLE sub_project');
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E3AA68C51');
        $this->addSql('DROP INDEX IDX_F981B52E3AA68C51');
        $this->addSql('ALTER TABLE chapter DROP sub_project_id');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A763AA68C51');
        $this->addSql('DROP INDEX IDX_D8698A763AA68C51');
        $this->addSql('ALTER TABLE document DROP sub_project_id');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA73AA68C51');
        $this->addSql('DROP INDEX IDX_378DFDA73AA68C51');
        $this->addSql('ALTER TABLE interaction DROP sub_project_id');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE3AA68C51');
        $this->addSql('DROP INDEX IDX_2FB3D0EE3AA68C51');
        $this->addSql('ALTER TABLE project DROP sub_project_id');
        $this->addSql('ALTER TABLE research_project DROP is_template');
        $this->addSql('ALTER TABLE research_project RENAME COLUMN title TO name');
    }
}
