<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704082225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bibliography_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cite_key VARCHAR(100) NOT NULL, entry_type VARCHAR(30) DEFAULT \'misc\' NOT NULL, title TEXT DEFAULT NULL, authors TEXT DEFAULT NULL, year VARCHAR(10) DEFAULT NULL, journal VARCHAR(255) DEFAULT NULL, doi VARCHAR(255) DEFAULT NULL, raw_data JSON DEFAULT NULL, source VARCHAR(20) DEFAULT \'bib_file\' NOT NULL, zotero_key VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sub_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B52B83B3AA68C51 ON bibliography_entry (sub_project_id)');
        $this->addSql('CREATE INDEX IDX_7B52B83B2B6ABA2 ON bibliography_entry (cite_key)');
        $this->addSql('ALTER TABLE bibliography_entry ADD CONSTRAINT FK_7B52B83B3AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bibliography_entry DROP CONSTRAINT FK_7B52B83B3AA68C51');
        $this->addSql('DROP TABLE bibliography_entry');
    }
}
