<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704193846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bibliographic_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cite_key VARCHAR(100) NOT NULL, entry_type VARCHAR(30) DEFAULT \'misc\' NOT NULL, title TEXT DEFAULT NULL, authors TEXT DEFAULT NULL, year VARCHAR(10) DEFAULT NULL, journal VARCHAR(255) DEFAULT NULL, doi VARCHAR(255) DEFAULT NULL, raw_data JSON DEFAULT NULL, source VARCHAR(20) DEFAULT \'bib_file\' NOT NULL, zotero_key VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99946120A76ED395 ON bibliographic_reference (user_id)');
        $this->addSql('CREATE INDEX IDX_999461202B6ABA2 ON bibliographic_reference (cite_key)');
        $this->addSql('CREATE TABLE project_bibliography (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, research_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6E8050BD27719F4 ON project_bibliography (research_project_id)');
        $this->addSql('CREATE INDEX IDX_A6E8050BD27719F4 ON project_bibliography (research_project_id)');
        $this->addSql('CREATE TABLE project_bibliography_bibliographic_reference (project_bibliography_id INT NOT NULL, bibliographic_reference_id INT NOT NULL, PRIMARY KEY (project_bibliography_id, bibliographic_reference_id))');
        $this->addSql('CREATE INDEX IDX_452B4A2B9B2B478 ON project_bibliography_bibliographic_reference (project_bibliography_id)');
        $this->addSql('CREATE INDEX IDX_452B4A2D5888EF2 ON project_bibliography_bibliographic_reference (bibliographic_reference_id)');
        $this->addSql('ALTER TABLE bibliographic_reference ADD CONSTRAINT FK_99946120A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_bibliography ADD CONSTRAINT FK_A6E8050BD27719F4 FOREIGN KEY (research_project_id) REFERENCES research_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_bibliography_bibliographic_reference ADD CONSTRAINT FK_452B4A2B9B2B478 FOREIGN KEY (project_bibliography_id) REFERENCES project_bibliography (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_bibliography_bibliographic_reference ADD CONSTRAINT FK_452B4A2D5888EF2 FOREIGN KEY (bibliographic_reference_id) REFERENCES bibliographic_reference (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bibliographic_reference DROP CONSTRAINT FK_99946120A76ED395');
        $this->addSql('ALTER TABLE project_bibliography DROP CONSTRAINT FK_A6E8050BD27719F4');
        $this->addSql('ALTER TABLE project_bibliography_bibliographic_reference DROP CONSTRAINT FK_452B4A2B9B2B478');
        $this->addSql('ALTER TABLE project_bibliography_bibliographic_reference DROP CONSTRAINT FK_452B4A2D5888EF2');
        $this->addSql('DROP TABLE bibliographic_reference');
        $this->addSql('DROP TABLE project_bibliography');
        $this->addSql('DROP TABLE project_bibliography_bibliographic_reference');
    }
}
