<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630162729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE editor_interaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, selected_text TEXT DEFAULT NULL, suggestion TEXT DEFAULT NULL, accepted BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sub_project_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1ED9518B3AA68C51 ON editor_interaction (sub_project_id)');
        $this->addSql('CREATE INDEX IDX_1ED9518BA76ED395 ON editor_interaction (user_id)');
        $this->addSql('CREATE INDEX IDX_1ED9518B8B8E8428 ON editor_interaction (created_at)');
        $this->addSql('ALTER TABLE editor_interaction ADD CONSTRAINT FK_1ED9518B3AA68C51 FOREIGN KEY (sub_project_id) REFERENCES sub_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE editor_interaction ADD CONSTRAINT FK_1ED9518BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ALTER roles DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE editor_interaction DROP CONSTRAINT FK_1ED9518B3AA68C51');
        $this->addSql('ALTER TABLE editor_interaction DROP CONSTRAINT FK_1ED9518BA76ED395');
        $this->addSql('DROP TABLE editor_interaction');
        $this->addSql('ALTER TABLE "user" ALTER roles SET DEFAULT \'[]\'');
    }
}
