<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627025333 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE research_project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(10) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B61D60F4A76ED395 ON research_project (user_id)');
        $this->addSql('ALTER TABLE research_project ADD CONSTRAINT FK_B61D60F4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD research_project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EED27719F4 FOREIGN KEY (research_project_id) REFERENCES research_project (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_2FB3D0EED27719F4 ON project (research_project_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE research_project DROP CONSTRAINT FK_B61D60F4A76ED395');
        $this->addSql('DROP TABLE research_project');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EED27719F4');
        $this->addSql('DROP INDEX IDX_2FB3D0EED27719F4');
        $this->addSql('ALTER TABLE project DROP research_project_id');
    }
}
