<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260516141430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chapter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, "order" INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F981B52E166D1F9C ON chapter (project_id)');
        $this->addSql('CREATE INDEX IDX_F981B52E727ACA70 ON chapter (parent_id)');
        $this->addSql('CREATE TABLE daily_metrics (date DATE NOT NULL, active_users INT NOT NULL, new_registrations INT NOT NULL, ia_requests_total INT NOT NULL, ia_requests_literature INT NOT NULL, ia_requests_reading INT NOT NULL, ia_requests_writing INT NOT NULL, ia_requests_thesis INT NOT NULL, files_uploaded INT NOT NULL, avg_deepseek_response_ms INT NOT NULL, error_count INT NOT NULL, exports_count INT NOT NULL, PRIMARY KEY (date))');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, stored_path VARCHAR(512) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, is_scanned BOOLEAN DEFAULT false NOT NULL, virus_found BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76166D1F9C ON document (project_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76A76ED395 ON document (user_id)');
        $this->addSql('CREATE TABLE interaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, user_prompt TEXT NOT NULL, ai_response TEXT DEFAULT NULL, response_time_ms INT DEFAULT NULL, tokens_used INT DEFAULT NULL, cost_cfa NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_378DFDA7166D1F9C ON interaction (project_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_accessed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEA76ED395 ON project (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, orcid VARCHAR(19) DEFAULT NULL, affiliation VARCHAR(255) DEFAULT NULL, research_field VARCHAR(255) DEFAULT NULL, theme_preference VARCHAR(10) DEFAULT \'light\' NOT NULL, language_preference VARCHAR(2) DEFAULT \'fr\' NOT NULL, help_enabled BOOLEAN DEFAULT true NOT NULL, trial_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649A8077F40 ON "user" (orcid)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E727ACA70 FOREIGN KEY (parent_id) REFERENCES chapter (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E166D1F9C');
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E727ACA70');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76166D1F9C');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76A76ED395');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7166D1F9C');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEA76ED395');
        $this->addSql('DROP TABLE chapter');
        $this->addSql('DROP TABLE daily_metrics');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE interaction');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE "user"');
    }
}
