services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Service\Bibliography\BibliographicReferenceManager: ~
    App\Service\Bibliography\BibtexImporter: ~
    App\Service\Bibliography\DoiResolver: ~
